### ISSUE TITLE
Would be it possible to create react-dnd react-native backend?

### ISSUE THREAD

**Issue by krtr** [sharingapples/react-native-dnd#1]
I'm just wondering

**Comment by syaau** [comment]
I didn't really get your point.

**Comment by syaau** [comment]
If you are talking about react-dnd by gaeron, I guess it's possible, but I didn't find a good documentation on creating a backend.

**Comment by krtr** [comment]
React-dnd is well known library for dealing with dnd stuff, and has ability to swap backends, for example 
It is using "by default" https://github.com/gaearon/react-dnd-html5-backend
but can be also configured to use https://github.com/yahoo/react-dnd-touch-backend

Do you think that it is possible to make backend for react-native?

**Comment by krtr** [comment]
ok thx
